# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7a89aeb9771ce9f698b012f21b8d822d20f8d0852bd95e990f44adde204cf1e190e2ff04faf0cf459a0781ceb563f5bcb698ea038f6d73974b6e68f19cb4611

test:
  secret_key_base: bba77d4d51440a7f3c6290d80ceb436fafa243c7208872421963fa97e7849f41c9d91189197c0403e6e20a32f98f34bdffa3137b8aaf6b76a22abca2b6cc38b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
